#FROM grafana/grafana:latest

FROM grafana/grafana:9.5.1
#FROM grafana/grafana:10.2.3

# Set Grafana options
ENV GF_ENABLE_GZIP=true
ENV GF_USERS_DEFAULT_THEME=dark
ENV GF_FEATURE_TOGGLES_ENABLE=topnav

## Enable Anonymous Authentication
#ENV GF_AUTH_ANONYMOUS_ENABLED=true
#ENV GF_AUTH_BASIC_ENABLED=false

## Disable Sanitize
#ENV GF_PANELS_DISABLE_SANITIZE_HTML=true

## Disable Explore
#ENV GF_EXPLORE_ENABLED=false

## Disable Alerting
#ENV GF_ALERTING_ENABLED=false
#ENV GF_UNIFIED_ALERTING_ENABLED=false

# Home Dashboard
#COPY /supervisor.json /var/lib/docker/overlay2/e5011136a41996896eb77e31995609e06cd1c7248b68ad6245b79bf84b09ac93/merged/etc/grafana/provisioning/dashboards/supervisor.json
#COPY /supervisor.json /etc/grafana/provisioning/dashboards/supervisor.json
#ENV GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH=/etc/grafana/provisioning/dashboards/supervisor.json
#ENV GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH=/var/lib/docker/overlay2/e5011136a41996896eb77e31995609e06cd1c7248b68ad6245b79bf84b09ac93/merged/etc/grafana/provisioning/dashboards/supervisor.json
#COPY /supervisor.json $GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH


ENV GF_PATHS_CONFIG="/etc/grafana/grafana.ini"
ENV GF_PATHS_DATA="/var/lib/grafana"
ENV GF_PATHS_HOME="/usr/share/grafana"
ENV GF_PATHS_LOGS="/var/log/grafana"

# Paths
#ENV GF_PATHS_PROVISIONING="/var/lib/docker/overlay2/e5011136a41996896eb77e31995609e06cd1c7248b68ad6245b79bf84b09ac93/merged/etc/grafana/provisioning"
ENV GF_PATHS_PROVISIONING="/etc/grafana/provisioning"
ENV GF_PATHS_PLUGINS="/var/lib/grafana/plugins"
ENV GF_PATHS_IMG="/usr/share/grafana/public/img"
#ENV GF_PATHS_PLUGINS="/var/lib/docker/overlay2/e5011136a41996896eb77e31995609e06cd1c7248b68ad6245b79bf84b09ac93/merged/var/lib/grafana/plugins"

# Copy artifacts
 #COPY --chown=grafana:root dist /app
 #COPY entrypoint.sh / 

# Provisioning
#COPY --chown=grafana:root provisioning $GF_PATHS_PROVISIONING

###### Customization ########################################
USER root

# Replace Faviconpu
COPY /img/fav32.png /usr/share/grafana/public/img/fav32.png
# COPY img/fav32.png /usr/share/grafana/public/img/apple-touch-icon.png

# Replace Logo
COPY /img/grafana.svg /usr/share/grafana/public/img/grafana.svg
COPY /img/logo.svg /usr/share/grafana/public/img/grafana_icon.svg

# Background
# COPY img/background.svg /usr/share/grafana/public/img/g8_login_dark.svg
# COPY img/background.svg /usr/share/grafana/public/img/g8_login_light.svg

# Update Javascript
## Update Title
RUN find /usr/share/grafana/public/build/ -name *.js -exec sed -i 's|AppTitle="Grafana"|AppTitle="Hape"|g' {} \;

## Update Login Title
RUN find /usr/share/grafana/public/build/ -name *.js -exec sed -i 's|LoginTitle="Welcome to Grafana"|LoginTitle="Hape IoT"|g' {} \;

## Remove Documentation, Support, Community in the Footer
RUN find /usr/share/grafana/public/build/ -name *.js -exec sed -i 's|\[{target:"_blank",id:"documentation".*grafana_footer"}\]|\[\]|g' {} \;

## Remove Edition in the Footer
RUN find /usr/share/grafana/public/build/ -name *.js -exec sed -i 's|({target:"_blank",id:"version",.*licenseUrl})|()|g' {} \;

## Remove Version in the Footer
RUN find /usr/share/grafana/public/build/ -name *.js -exec sed -i 's|({target:"_blank",id:"version",.*CHANGELOG.md":void 0})|()|g' {} \;

## Remove New Version is available in the Footer
RUN find /usr/share/grafana/public/build/ -name *.js -exec sed -i 's|({target:"_blank",id:"updateVersion",.*grafana_footer"})|()|g' {} \;

## Update Search Place holder in the Top Navigation
RUN find /usr/share/grafana/public/build/ -name *.js -exec sed -i 's|("nav.search.placeholder","Search Grafana")|("nav.search.placeholder","Search")|g' {} \;
##################################################################


## wyczysc link do grafany zmien na hape
# RUN find /usr/share/grafana/public/build/ -name *.js -exec sed -i 's|(href: "https://grafana.com/docs/grafana/latest/dashboards/time-range-controls")|(href: "https://hape-heatpumps.eu")|g' {} \;
RUN find /usr/share/grafana/public/build/ -name *.js -exec sed -i 's|"https://grafana.com/docs/grafana/latest/dashboards/time-range-controls"|"https://hape-heatpumps.eu"|g' {} \;

# RUN find /usr/share/grafana/public/build/ -name *.css -exec sed -i 's|.submenu-controls{display:none}@media(max-width:768px){nav.page-toolbar--fullscreen{padding-left:16px}}|.submenu-controls{display:none}@media(max-width:768px){nav.page-toolbar--fullscreen{padding-left:16px}}.css-13883cc{display:none !important} .panel-title{display:none !important}.css-1opalb8{display: none !important}.css-nqsyso{display:none !important}.sidemenu{display:none !important}.react-resizable-handle{display:none !important}.css-ta03ya:nth-child(0){display:none !Important}.css-ta03ya:nth-child(1){display:none !important}.css-ta03ya:nth-child(2){display:none !important}.css-ta03ya:nth-child(3){display:none !important}.css-1bycjdg{display:none !important}.css-69gxti-toolbar-button{display:none !important}.css-rwrh9q{display:none !important}.css-1hiexmr:nth-child(1){display:none !important}.css-1hiexmr:nth-child(2){display:none !important}|g' {} \;

# RUN find /usr/share/grafana/public/build/ -name *.css -exec sed -i 's|(.submenu-controls{display:none}@media(max-width:768px){nav.page-toolbar--fullscreen{padding-left:16px}})|(.submenu-controls{display:none}@media(max-width:768px){nav.page-toolbar--fullscreen{padding-left:16px}}.css-13883cc{display:none !important} .panel-title{display:none !important}.submenu-controls{display:none !important}.css-1opalb8{display: none !important}.css-nqsyso{display:none !important}.sidemenu{display:none !important}.react-resizable-handle{display:none !important}.css-ta03ya:nth-child(0){display:none !Important}.css-ta03ya:nth-child(1){display:none !important}.css-ta03ya:nth-child(2){display:none !important})|g' {} \;

# RUN find /usr/share/grafana/public/build/ -name *.js -exec sed -i 's|{target:"_blank",id:"documentation",text:(0,r.t)("nav.help/documentation","Documentation"),icon:"document-info",url:"https://grafana.com/docs/grafana/latest/?utm_source=grafana_footer"},{target:"_blank",id:"support",text:(0,r.t)("nav.help/support","Support"),icon:"question-circle",url:"https://grafana.com/products/enterprise/?utm_source=grafana_footer"},{target:"_blank",id:"community",text:(0,r.t)("nav.help/community","Community"),icon:"comments-alt",url:"https://community.grafana.com/?utm_source=grafana_footer"}||g' {} \;

# RUN find /usr/share/grafana/public/build/ -name *.js -exec sed -i 's|{target:"_blank",id:"version",text:`${e.edition}${s}`,url:t.licenseUrl}||g' {} \;
# RUN find /usr/share/grafana/public/build/ -name *.js -exec sed -i 's|{target:"_blank",id:"version",text:`v${e.version} (${e.commit})`,url:i?"https://github.com/grafana/grafana/blob/main/CHANGELOG.md":void 0}||g' {} \;
# RUN find /usr/share/grafana/public/build/ -name *.js -exec sed -i 's|{target:"_blank",id:"updateVersion",text:"New version available!",icon:"download-alt",url:"https://grafana.com/grafana/download?utm_source=grafana_footer"}||g' {} \;

#############################################################

# USER grafana

# Entrypoint
# ENTRYPOINT [ "/bin/bash", "/entrypoint.sh" ]